title: Jasmine Lo # your name (or website title) here
logo: "jasicon.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An aspiring data analyst who is passionate about telling stories and solving problems through data.   
  <br><br>
  I value data-driven decision-making, attention to detail and exploring life with a growth mindset.  
  <br><br>
  <a href="http://www.linkedin.com/in/jasmine-l-a4013a22b">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
